### ISSUE TITLE
(Go) constants should be MixedCaps, not ALLCAPS

### ISSUE THREAD

**Issue by extemporalgenome** [cznic/cc#1]
https://github.com/golang/go/wiki/CodeReviewComments#mixed-caps

This is also something that golint would report.

**Comment by cznic** [comment]
Thanks for the report.

Do you mean the [token symbolic names](https://github.com/cznic/cc/blob/68bd3534d4e230659060b5aff1886a4c3297a67c/parser.go#L68)?

Both you and `golint` are right (and I do run golint on [`make`](https://github.com/cznic/cc/blob/68bd3534d4e230659060b5aff1886a4c3297a67c/Makefile#L9)). But there's a decades long convention of using all-caps token symbolic identifiers in `yacc` files. Many people, me included, are so used to that convention, that reading a yacc file not following that convention becomes hard. Possible to read, but requiring an extra effort.

The convention can be seen even in the [go/token package](https://godoc.org/go/token#Token).

While the Go compiler still used a yacc generated parser, the convention was [used as well](https://github.com/golang/go/blob/release-branch.go1.5/src/cmd/compile/internal/gc/y.go#L23).

Today the Go compiler uses a hand written lexer/parser, but the convention [is still there](https://github.com/golang/go/blob/596df2424d1304442dbb5f5aa4eab153013d4d50/src/cmd/compile/internal/gc/lex.go#L911).
