### ISSUE TITLE
A MustConvert case for unsigned long, ULong is missing.

### ISSUE THREAD

**Issue by xlab** [cznic/cc#4]
```
panic: internal error unsigned long, ULong

goroutine 1 [running]:
panic(0x362fe0, 0xc82024f310)
	/usr/local/go/src/runtime/panic.go:464 +0x3e6
github.com/cznic/cc.(*Model).MustConvert(0x630b20, 0x2fa4e0, 0xc82024f2b4, 0x707a60, 0xc820482720, 0x0, 0x0)
	/Users/xlab/Documents/dev/go/src/github.com/cznic/cc/model.go:591 +0xa57
github.com/cznic/cc.(*Expression).eval(0xc8207a0c00, 0xc8203583c0, 0x0, 0x0, 0x0, 0x0)
	/Users/xlab/Documents/dev/go/src/github.com/cznic/cc/ast2.go:729 +0x38eb
```

**Comment by xlab** [comment]
Let me know if an example will help you in any way, they are hard to fetch so I don't provide them by default..

**Comment by cznic** [comment]
> Let me know if an example will help you in any way, they are hard to fetch due to a panic so I don't provide them by default..

In this case an example is not necessary, the change is simple. Reviewed https://github.com/cznic/cc/commit/a48e6f89ac5d3faab810c2c298b46fbc44a7b9df, LGTM. Thanks.
