### ISSUE TITLE
Overflow in enumeration value: 4294967040

### ISSUE THREAD

**Issue by xlab** [cznic/cc#48]
Having this enum:
```C
enum {
    AINPUT_SOURCE_UNKNOWN = 0x00000000,
    AINPUT_SOURCE_ANY = 0xffffff00,
};
```

It seems that CC tries to handle `0xffffff00` as `int32`, you previously have said:
> I've made enum types have always the properties of C int. The reason is that the C99 specification mandates that the enum const expression value must be representable as C int.

But from C99 §6.7.2.2/4:
> Each enumerated type shall be compatible with char, a signed integer type, or an unsigned integer type. The choice of type is implementation-defined but shall be capable of representing the values of all the members of the enumeration.

So in this case it must be treated as `uint32` and be represented with no issues.

**Comment by xlab** [comment]
I could fix this by replacing 

```go
var ok bool
if v, ok = m.toInt(e.Value); !ok {
	lx.report.Err(e.Pos(), "overflow in enumeration value: %v", e.Value)
}
```

by

```
v = m.MustConvert(e.Value, m.IntType)
```

just FYI ;)

**Comment by xlab** [comment]
P.S. I decided to dig a bit deeper and check the `(m *Model) toInt(v interface{}) (interface{}, bool)`
which seems to have bounds check on `math.MaxInt32` rather than `math.MaxUint64`, so this is clear now.

**Comment by cznic** [comment]
> P.S. I decided to dig a bit deeper and check the (m *Model) toInt(v interface{}) (interface{}, bool)
which seems to have bounds check on math.MaxInt32 rather than math.MaxUint64, so this is clear now.

Well, now I don't know if there's something to fix or not. In any case, C99 §6.7.2.2/2:

> The expression that defines the value of an enumeration constant shall be an integer
constant expression that has a value representable as an int.

By convention `int` is presumed by `cc` to be 32 bits even in 64 bit models, even though `Model` can define its size to be 64 bits. Then a lot of things inside `cc` will break. So that is a bug, I think.

Please let me know if you need this problem to be resolved and suggest anything relevant to the proper solution. I'll then try to fix what I fix can ;-)

**Comment by xlab** [comment]
Enums must not fail on overflow with an uint32 value. So for myself I made this fix:

```diff
diff --git a/model.go b/model.go
index c86ee01..814ef93 100644
--- a/model.go
+++ b/model.go
@@ -165,7 +165,7 @@ func (m *Model) toInt(v interface{}) (interface{}, bool) {
        case uint32:
                switch sz := m.Items[Int].Size; sz {
                case 4:
-                       return m.MustConvert(x, m.IntType), x <= math.MaxInt32
+                       return m.MustConvert(x, m.IntType), x <= math.MaxUint32
                case 8:
                        return m.MustConvert(x, m.IntType), true
                default:
@@ -174,7 +174,7 @@ func (m *Model) toInt(v interface{}) (interface{}, bool) {
        case int64:
                switch sz := m.Items[Int].Size; sz {
                case 4:
-                       return m.MustConvert(x, m.IntType), x <= math.MaxInt32
+                       return m.MustConvert(x, m.IntType), x <= math.MaxUint32
                case 8:
                        return m.MustConvert(x, m.IntType), true
                default:
@@ -183,9 +183,9 @@ func (m *Model) toInt(v interface{}) (interface{}, bool) {
        case uint64:
                switch sz := m.Items[Int].Size; sz {
                case 4:
-                       return m.MustConvert(x, m.IntType), x <= math.MaxInt32
+                       return m.MustConvert(x, m.IntType), x <= math.MaxUint32
                case 8:
-                       return m.MustConvert(x, m.IntType), x <= math.MaxInt64
+                       return m.MustConvert(x, m.IntType), x <= math.MaxUint64
                default:
                        panic(sz)
                }
```

Which works fine. The `toInt` method being used for enums only. So the constant values here are representable as int but **are compatible with char aka unsigned int**.

**Comment by cznic** [comment]
OK, I think I finally understand it now, thank you.

Do you want to fix `cc` directly by yourself (you have the access rights) or do you prefer me to incorporate the diff you provided above?

**Comment by cznic** [comment]
Thank you.
