### ISSUE TITLE
HostConfig must respect cpp path overrides

### ISSUE THREAD

**Issue by xlab** [cznic/cc#49]
I'm creating a ticket for the discussion we had by email. So the problem is that HostConfig aims for `cpp` and does not respect any overrides via `CPP` env variable for example.

```go
func HostConfig(opts ...string) (predefined string, includePaths, sysIncludePaths []string, err error) {
	args := append(append([]string{"-dM"}, opts...), "/dev/null")
	pre, err := exec.Command("cpp", args...).Output()
	if err != nil {
		return "", nil, nil, err
	}
...
```

My suggestion is to do it like this:

```go
cppPath := "cpp"
if path, ok := os.LookupEnv("CPP"); ok {
    cpPath = path
}
pre, err := exec.Command(cppPath, ...
```

**Comment by xlab** [comment]
But the way, on the second thought I'm not happy with os.LookupEnv being called from as shared package, so probably this path argument should come as an argument to HostConfig from the outside main or something.

But the case is too specific to make it that "100% correct" way.

**Comment by cznic** [comment]
@xlab PTAL.

**Comment by xlab** [comment]
👍🏻

**Comment by cznic** [comment]
> 👍🏻

I can see only non readable character(s) on my display ;-)

You have closed the issue without merging the branch. Please let me know if the patch is okay for you and if I should merge the `issue49` branch. Thank you.

**Comment by xlab** [comment]
Sorry, still getting used to this flow. Yes, changes are looking good to me, feel free to merge the branch.

**Comment by cznic** [comment]
No problem ;-)

Merged.
