### ISSUE TITLE
No /dev/null under Windows

### ISSUE THREAD

**Issue by xlab** [cznic/cc#58]
Hi! I discovered this issue while using CC host config option under Windows MinGW environment:

```go
func HostCppConfig(cpp string, opts ...string) (predefined string, includePaths, sysIncludePaths []string, err error) {
	args := append(append([]string{"-dM"}, opts...), "/dev/null")
...
```
Uses `/dev/null` that's not available under windows. It must be `nul` instead.
This bug is easy to fix, however I want your opinion because this is design-specific.

I would use `runtime.GOOS`.

**Comment by xlab** [comment]
One more thing though:

```go
a := strings.Split(string(out), "\n")
```

should be

```go
a := strings.Split(string(out), "\r\n")
```
under Windows. I tried, it works.

**Comment by cznic** [comment]
Hi Max, on the road ATM, please feel free to make the change as suggested, thank you.

**Comment by cznic** [comment]
@xlab Gentle ping.

**Comment by xlab** [comment]
Fixed by @steffengy, thanks.
