### ISSUE TITLE
Unexpected `:` in macro def

### ISSUE THREAD

**Issue by xlab** [cznic/cc#59]
Hey! Getting an error of unexpected `:` —
```
include\_mingw.h:542:34: unexpected ':', expected one of [!=, %=, &&, &=, '%', '&', '(', ')', '*', '+', ',', '-', '.', '/', '<', '=', '>', '?', '[', '^', '|', *=, ++, +=, —, -=, ->, /=, «, «=, <=, ==, >=, », »=, ^=, |=, ||]
```

It appears in this code:

```c
#ifdef __MINGW_INTRIN_INLINE
#if !defined (__clang__)
void __cdecl __debugbreak(void);
__MINGW_INTRIN_INLINE void __cdecl __debugbreak(void)
{
  __asm__ __volatile__("int {$}3":);
}
#endif
#endif
```

Any easy solution to avoid the parsing anyhow? Disabling the define doesn't help much.

**Comment by cznic** [comment]
@xlab Please try https://github.com/cznic/cc/commit/967cfb920e2c0f0e43fc0f0316a52cd56c228e5e, thank you.

**Comment by xlab** [comment]
This seems to be working, thanks!

**Comment by cznic** [comment]
Closed by https://github.com/cznic/cc/commit/fd6d609a567a6a57f5a5dffa84e4df482df687c8.
