### ISSUE TITLE
unexpected EOF

### ISSUE THREAD

**Issue by xlab** [cznic/cc#61]
While running CC under Windows (!) I've managed to resolve all issues, but this one:

```
unexpected EOF, unexpected EOF
unexpected EOF, unexpected EOF
unexpected EOF, unexpected EOF
unexpected EOF, unexpected EOF
unexpected EOF, unexpected EOF
unexpected EOF, unexpected EOF
unexpected EOF, unexpected EOF
unexpected EOF, unexpected EOF
unexpected EOF, unexpected EOF
unexpected EOF, unexpected EOF
too many errors
```

How can I debug this? How to organise error line reporting or something, I don't have any clue :(

**Comment by xlab** [comment]
And trying to compile windows headers on OS X, leads me to the same thing:

```
unexpected EOF, unexpected EOF (and 8 more errors)
```

**Comment by cznic** [comment]
> How can I debug this? 

I think we shall start by having a reproduction case ;-)

However, no Windows or OS X here. Maybe I can infer something from the reproduction case, if it will be small...

> still no clue how to debug. 

Look for the report object, set it's [`PanicOnError`](https://godoc.org/github.com/cznic/xc#Report) property to true, paste the stack trace here.

(Should become an standard option.)

**Comment by cznic** [comment]
@xlab Gentle ping.

**Comment by xlab** [comment]
I forgot what this was about.
