### ISSUE TITLE
bit field has invalid type (have unsigned long long)

### ISSUE THREAD

**Issue by pwaller** [cznic/cc#74]
```
/usr/include/linux/perf_event.h:309:23: bit field has invalid type (have unsigned long long)
```

<details>

```c
struct perf_event_attr {
	unsigned long long			disabled       :  1, /* off by default        */
				inherit	       :  1, /* children inherit it   */
				pinned	       :  1, /* must always be on PMU */
				exclusive      :  1, /* only group on PMU     */
				exclude_user   :  1, /* don't count user      */
				exclude_kernel :  1, /* ditto kernel          */
				exclude_hv     :  1, /* ditto hypervisor      */
				exclude_idle   :  1, /* don't count when idle */
				mmap           :  1, /* include mmap data     */
				comm	       :  1, /* include comm data     */
				freq           :  1, /* use freq, not period  */
				inherit_stat   :  1, /* per task counts       */
				enable_on_exec :  1, /* next exec enables     */
				task           :  1, /* trace fork/exit       */
				watermark      :  1, /* wakeup_watermark      */
				/*
				 * precise_ip:
				 *
				 *  0 - SAMPLE_IP can have arbitrary skid
				 *  1 - SAMPLE_IP must have constant skid
				 *  2 - SAMPLE_IP requested to have 0 skid
				 *  3 - SAMPLE_IP must have 0 skid
				 *
				 *  See also PERF_RECORD_MISC_EXACT_IP
				 */
				precise_ip     :  2, /* skid constraint       */
				mmap_data      :  1, /* non-exec mmap data    */
				sample_id_all  :  1, /* sample_type all events */

				exclude_host   :  1, /* don't count in host   */
				exclude_guest  :  1, /* don't count in guest  */

				exclude_callchain_kernel : 1, /* exclude kernel callchains */
				exclude_callchain_user   : 1, /* exclude user callchains */
				mmap2          :  1, /* include mmap with inode data     */
				comm_exec      :  1, /* flag comm events that are due to an exec */
				use_clockid    :  1, /* use @clockid for time fields */
				context_switch :  1, /* context switch data */
				write_backward :  1, /* Write ring buffer from end to beginning */
				__reserved_1   : 36;
}
```
</details>

Fix incoming.

**Comment by cznic** [comment]
I think bit fields can be only `int` or `uint` typed, but I am not sure. Have to check the standard (or please look into it if you happen to have some free time). If it is non-standard, then I would probably add an `Option` for that. What do you think?

**Comment by pwaller** [comment]
Of course it's not the standard, but it is used [here in the linux kernel](https://github.com/torvalds/linux/blob/69973b830859bc6529a7a0468ba0d80ee5117826/tools/include/uapi/linux/perf_event.h#L308-L347).

I'm still just getting to grips with `cc`, so I couldn't weigh in on what makes sense yet.

**Comment by andlabs** [comment]
`<details>` is interesting; didn't know about that. Cool!

C99, §6.7.2.1 paragraph 4 (page 102):

>A bit-field shall have a type that is a qualified or unqualified version of **`_Bool`**, **`signed int`**, **`unsigned int`**, or some other implementation-defined type.

I am not sure what the standard means by "qualified or unqualified version". Not sure if C11 makes anything any clearer.

**Comment by pwaller** [comment]
Ha, I just found the same paragraph.

So, is this patch OK? ("Implementation defined, heh...")

**Comment by cznic** [comment]
I would like to be conservative by default, but I see no problem with enabling more/non-standard features on demand. Suggested approach:

- Extend [tweaks](https://github.com/cznic/cc/blob/533ca70c55a2970885094ae5e68eb27588f7ffc7/cc.go#L136) with a new `bool` field enabling it. 
- Add a new [`Opt`](https://github.com/cznic/cc/blob/533ca70c55a2970885094ae5e68eb27588f7ffc7/cc.go#L274) to the API.
- Add a case to this [`switch`](https://github.com/cznic/cc/blob/533ca70c55a2970885094ae5e68eb27588f7ffc7/ast2.go#L2136) that enables the wider types when the respective tweak flag is set.

**Comment by andlabs** [comment]
Ah yes, "qualified or unqualified versions" refers to the type qualifiers `const`, `restrict`, and `volatile` (§6.2.5 paragraph 25 (page 36)). I've never seen a qualified bit field before, and I wonder how it'd be used...

**Comment by cznic** [comment]
Well, eg. `volatile` makes sense for memory mapped I/O register bits ;-)

**Comment by pwaller** [comment]
@xlab I'm wanting to use this with cgogen. Is it possible to pass opts to `cc` via the yml definition?

**Comment by cznic** [comment]
> @xlab I'm wanting to use this with cgogen. Is it possible to pass opts to cc via the yml definition?

I!m afraid that's not the case but `cgogen` already enables some options by default so one solution would be to add it [here](https://github.com/xlab/cgogen/blob/7a09e14c20ee9bc4a698c735ed4b887a66e8730a/parser/parser.go#L100).

**Comment by xlab** [comment]
@pwaller Jan is right, I'm trying to enable all extensions supported by CC, because cgogen must be able to parse anything and the compilation itself is a duty of host compiler so I don't care too much about non-standard extensions.

/cc @cznic

**Comment by pwaller** [comment]
@xlab: Once the new features are merged, I will submit a PR to cgogen to enable them.
