### ISSUE TITLE
Wrong Type, Elements() and Sizeof() for `char s[] = "foo";`

### ISSUE THREAD

**Issue by cznic** [cznic/cc#80]
```c
char s[] = "foo";
```

is equivalent to

```c
char s[4] = "foo"; // Number of elements includes the trailing zero byte of the string.
```

**Comment by andlabs** [comment]
Does this keep

```
const char *s = "foo";
```

working correctly?

**Comment by cznic** [comment]
@andlabs  Commit https://github.com/cznic/cc/commit/de04c94a745057569d8d4323fbe84b0075dc952f broke that, commit https://github.com/cznic/cc/commit/a3aadec9423b927b47876fc80d1413d5541fcf13 should have fixed it again. Please confirm if it works/does not work for you now, thank you.

**Comment by andlabs** [comment]
I haven't tested it myself; I was just asking to make sure the edge cases were being handled :)

**Comment by cznic** [comment]
@andlabs 

> I haven't tested it myself; I was just asking to make sure the edge cases were being handled :)

Okay, np. And thanks for keeping an eye on the commits, really appreciated.

Nonetheless, turns out the patch broke another thing. Well, actually only unearthed an old [bug](https://github.com/cznic/cc/blob/b077eb0585ec454cd1a38c35417e26923d57eb61/parser.yy#L632):

```go
if !s.CanAssignTo(s) ...
```

Fix coming later today.
