### ISSUE TITLE
Comments with ` cause (probably) infinite loop

### ISSUE THREAD

**Issue by steffengy** [cznic/cc#93]
test.c (this only serves as something external that binds across files):
```c
#include "test.h"
extern int hello;

int main() { return 0; }
```

test.h (this is the relevant part):
```c
// abc using `typedef int size_t;` def
```

The compiler **most of the time hangs with using 15GB of RAM** on my system.
I think it crashed once though (since it's late at night I might be wrong there...)

~~References cznic/virtual#1~~

**Comment by steffengy** [comment]
Updated the issue since it's indeed another bug,
that's just related to some comment containing ` making the compiler hang. unfortunately.
So back to search.

**Comment by cznic** [comment]
I think someone had this problem before and it was fixed. AFAICT, it is not related to the backtick character, but that's just from a quick peek at `scanner.l`. Nowhere it seems to care about that character.

I'll be home in the evening, will then investigate and try to fix ASAP.

**Comment by steffengy** [comment]
@cznic 
It might be related to missing newlines of line-comments.
So if you're file consists only of `b"// test"` insteadof `b"//test\n"` it might be enough to crash,
that's atleast what I'm thinking of. 
Not at all critical, just noticed it while searching for something else.

**Comment by cznic** [comment]
@steffengy Thanks for the report, fixed.
